version: '3'

networks:
  whaticket:

services:

  app:
    image: node:14-alpine
    working_dir: /home/node/app
    command: sh -c "npm i && npm run dev:server"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - DB_NAME=${MYSQL_DATABASE:-whaticket}
      - JWT_SECRET=${JWT_SECRET:-3123123213123}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-75756756756}
      - BACKEND_URL=${BACKEND_URL:-http://localhost}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - PROXY_PORT=${PROXY_PORT:-8080}
      - CHROME_ARGS=--no-sandbox --disable-setuid-sandbox
    ports:
      - 3003:3003
    volumes:
      - ./public/:/usr/src/app/public/
      - ./.wwebjs_auth/:/usr/src/app/.wwebjs_auth/
      - .:/home/node/app
    networks:
      - whaticket
    depends_on:
      - mysql

  mysql:
    image: ${MYSQL_ENGINE:-mariadb}:${MYSQL_VERSION:-10.6}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin    
    volumes:
      - ./.docker/data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-whaticket}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-strongpassword}
      - TZ=${TZ:-America/Fortaleza}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    restart: always
    networks:
      - whaticket